import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const generateProjectPDF = (project, stats, activities) => {
    try {
        console.log("Generating PDF for:", project?.name);
        if (!project) {
            console.error("No project data provided for report");
            return;
        }

        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();

        // Helper: Header
        const addHeader = (title) => {
            doc.setFontSize(22);
            doc.setTextColor(79, 70, 229); // Indigo-600
            doc.text(title, 14, 22);

            doc.setDrawColor(229, 231, 235); // Gray-200
            doc.line(14, 28, pageWidth - 14, 28);
        };

        // Helper: Section Title
        const addSectionTitle = (title, y) => {
            doc.setFontSize(14);
            doc.setTextColor(31, 41, 55); // Gray-800
            doc.text(title, 14, y);
        };

        // --- Page 1: Overview ---
        addHeader("Project Executive Summary");

        doc.setFontSize(10);
        doc.setTextColor(107, 114, 128); // Gray-500
        doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 35);

        // Project Details
        addSectionTitle("Project Highlights", 45);

        const overviewData = [
            ["Project Name", project?.name || "N/A"],
            ["Status", "Active"],
            ["Total Members", stats?.[0]?.value || "0"],
            ["Completion", stats?.[3]?.value || "0%"],
            ["Active Tasks", stats?.[1]?.value || "0"],
            ["Pending Reviews", stats?.[2]?.value || "0"]
        ];

        autoTable(doc, {
            startY: 50,
            head: [["Metric", "Value"]],
            body: overviewData,
            theme: 'striped',
            headStyles: { fillColor: [79, 70, 229] },
            styles: { fontSize: 10 }
        });

        // Description
        addSectionTitle("Description", doc.lastAutoTable.finalY + 15);
        doc.setFontSize(10);
        doc.setTextColor(75, 85, 99); // Gray-600
        const splitDesc = doc.splitTextToSize(project.description || "No description provided.", pageWidth - 28);
        doc.text(splitDesc, 14, doc.lastAutoTable.finalY + 22);

        // --- Page 2: Activity Log ---
        doc.addPage();
        addHeader("Recent Activity Log");

        const activityData = (activities || []).map(act => [
            act.userName || "Unknown",
            act.action || "Action",
            act.targetName || "Target",
            act.createdAt ? new Date(act.createdAt).toLocaleDateString() : "N/A"
        ]);

        autoTable(doc, {
            startY: 35,
            head: [["User", "Action", "Target", "Date"]],
            body: activityData,
            theme: 'grid',
            headStyles: { fillColor: [79, 70, 229] },
            styles: { fontSize: 9 }
        });

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(156, 163, 175);
            doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
            doc.text("Generated by NEXUS Portal", 14, doc.internal.pageSize.getHeight() - 10);
        }

        doc.save(`${project.name.replace(/\s+/g, '_')}_Report.pdf`);
    } catch (error) {
        console.error("Error generating PDF:", error);
        alert("Failed to generate PDF. Please check the console for details.");
    }
};
